CREATE TABLE IF NOT EXISTS "Users" (
	"id" TEXT PRIMARY KEY NOT NULL,
	"device"	TEXT NOT NULL,
	"created_at"	DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "RefreshTokens" (
	"role"	TEXT,
	"refresh_token"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("refresh_token")
);

CREATE TABLE IF NOT EXISTS "Clipboard" (
	"id" INTEGER PRIMARY KEY AUTOINCREMENT,
	"from"	TEXT,
	"content"	TEXT NOT NULL,
	"created_at"	DATETIME DEFAULT CURRENT_TIMESTAMP
);